// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Reflective.Infrastructure.Persistence;

#nullable disable

namespace Reflective.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("Reflective.Domain.Entities.ActivityAggregate.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ActiveSessionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActiveSessionId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("Reflective.Domain.Entities.ActivityAggregate.ActivitySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("End")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Start")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.ToTable("ActivitySession");
                });

            modelBuilder.Entity("Reflective.Domain.Entities.ActivityAggregate.Activity", b =>
                {
                    b.HasOne("Reflective.Domain.Entities.ActivityAggregate.ActivitySession", "ActiveSession")
                        .WithMany()
                        .HasForeignKey("ActiveSessionId");

                    b.Navigation("ActiveSession");
                });

            modelBuilder.Entity("Reflective.Domain.Entities.ActivityAggregate.ActivitySession", b =>
                {
                    b.HasOne("Reflective.Domain.Entities.ActivityAggregate.Activity", "Activity")
                        .WithMany("Sessions")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Reflective.Domain.Entities.ActivityAggregate.Activity", b =>
                {
                    b.Navigation("Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
